-- MySQL Script generated by MySQL Workbench
-- Thu Jan  1 12:26:12 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema todolist
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema todolist
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `todolist` DEFAULT CHARACTER SET utf8 ;
USE `todolist` ;

-- -----------------------------------------------------
-- Table `todolist`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todolist`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `password` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`iduser`));


-- -----------------------------------------------------
-- Table `todolist`.`task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todolist`.`task` (
  `idtask` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  `status` ENUM('Hotovo', 'V prubehu') NOT NULL,
  `deadline` DATE NOT NULL,
  `user_iduser` INT NOT NULL,
  PRIMARY KEY (`idtask`, `user_iduser`),
  INDEX `fk_task_user_idx` (`user_iduser` ASC),
  CONSTRAINT `fk_task_user`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `todolist`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
